#!/bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           7

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc rule -a "jetbrains-idea" desktop='^1' state=floating
bspc rule -a Brave-browser desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a TelegramDesktop state=pseudo_tiled
bspc rule -a Skype desktop='^9' state=floating
bspc rule -a Gimp-2.10 desktop='^10' state=floating
bspc rule -a "Xfce4-power-manager-settings" state=floating
bspc rule -a "org-apache-jmeter-NewDriver" state=floating

# Border
bspc config focused_border_color        "#6c71c4"
bspc config normal_border_color         "#073642"
bspc config active_border_color         "#073642"

#
# Autostart
#
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &
# Bar
~/.config/polybar/launch.sh &
# Notifications
/usr/bin/dunst &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
# nitrogen --restore &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/
# Picom
picom --config /home/user/.config/picom.conf &
# Network Applet
nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &

# CAUTION: We are lying here
# to have java  applications support
wmname LG3D

# Change keyboard layout
setxkbmap -layout us,ru
setxkbmap -option 'grp:alt_shift_toggle'
killall -q gxkb
gxkb &
